[libraries]
yaci = "com.bloxbean.cardano:yaci:0.3.5"
cardano-client-lib = "com.bloxbean.cardano:cardano-client-lib:0.6.2"
cardano-client-backend = "com.bloxbean.cardano:cardano-client-backend:0.6.2"
cardano-client-backend-ogmios = "com.bloxbean.cardano:cardano-client-backend-ogmios:0.6.2"

cf-rewards="org.cardanofoundation:cf-rewards-calculation:1.0.0"

rocks-types="com.bloxbean:rocks-types:0.0.1-preview6"

cbor = "co.nstant.in:cbor:0.9"
hibernate-types = "io.hypersistence:hypersistence-utils-hibernate-63:3.7.1"
codehaus-janino = "org.codehaus.janino:janino:3.1.11"
guava = "com.google.guava:guava:33.0.0-jre"
springdoc-openapi-starter-webmvc-ui = "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0"
mapstruct="org.mapstruct:mapstruct:1.5.5.Final"
mapstruct-processor="org.mapstruct:mapstruct-processor:1.5.5.Final"

assertj-core="org.assertj:assertj-core:3.25.1"

spring-boot-admin-server="de.codecentric:spring-boot-admin-starter-server:3.2.1"
spring-boot-admin-client="de.codecentric:spring-boot-admin-starter-client:3.2.1"

rocksdb="org.rocksdb:rocksdbjni:8.9.1"
messagepack-jackson="org.msgpack:jackson-dataformat-msgpack:0.9.6"

parallel-collector="com.pivovarit:parallel-collectors:3.0.0"
apache-commons-pool="org.apache.commons:commons-pool2:2.12.0"

vavr="io.vavr:vavr:0.10.5"
