[libraries]
yaci = "com.bloxbean.cardano:yaci:0.3.0-beta8"
cardano-client-lib = "com.bloxbean.cardano:cardano-client-lib:0.5.0"
cardano-client-backend = "com.bloxbean.cardano:cardano-client-backend:0.5.0"
cardano-client-backend-ogmios = "com.bloxbean.cardano:cardano-client-backend-ogmios:0.5.0"
cbor = "co.nstant.in:cbor:0.9"
hibernate-types = "io.hypersistence:hypersistence-utils-hibernate-60:3.5.2"
codehaus-janino = "org.codehaus.janino:janino:3.1.8"
guava = "com.google.guava:guava:32.1.2-jre"
springdoc-openapi-starter-webmvc-ui = "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.0"
mapstruct="org.mapstruct:mapstruct:1.5.3.Final"
mapstruct-processor="org.mapstruct:mapstruct-processor:1.5.3.Final"

assertj-core="org.assertj:assertj-core:3.24.2"

spring-boot-admin-server="de.codecentric:spring-boot-admin-starter-server:3.1.8"
spring-boot-admin-client="de.codecentric:spring-boot-admin-starter-client:3.1.8"
