services:
  yaci-store-all:
    image: bloxbean/yaci-store-all:0.1.2
    container_name: yaci-store-all
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://yaci-store-postgres:5432/yaci_store?currentSchema=yaci_store}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-yaci}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-dbpass}
    env_file:
      - env
      - application.properties
    ports:
      - ${YAC_STORE_PORT:-8080}:8080
    volumes:
      - $PWD/logs:/app/logs/
      - ./application.properties:/app/config/application.properties
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

