version: '3.9'

networks:
  yaci-store-net:

services:
  yaci-store-postgres:
    extends:
      file: postgres-compose.yaml
      service: yaci-store-postgres
    networks:
      - yaci-store-net

  yaci-store-all:
    extends:
      file: yaci-store-all.yaml
      service: yaci-store-all
    depends_on:
      yaci-store-postgres:
        condition: service_healthy
    networks:
      - yaci-store-net
