services:
  yaci-store:
    image: bloxbean/yaci-store:${tag}
    container_name: yaci-store
    env_file:
      - ../config/env
    ports:
      - ${YACI_STORE_PORT:-8080}:8080
    volumes:
      - $PWD/logs:/app/logs/
      - ../config/application.properties:/app/config/application.properties
      - ../config/application-ledger-state.properties:/app/config/application-ledger-state.properties
      - ../config/application-plugins.yml:/app/config/application-plugins.yml
      - ../config/application-mcp.yml:/app/config/application-mcp.yml
      - ../plugins/scripts:/app/plugins/scripts/
      - ../plugins/ext-jars:/app/plugins/ext-jars/
      - ../plugins/files:/app/plugins/files/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"

